# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "C:\\Users\\57323\\Documents\\camilo_docs\\github\\learn_rust\\orm_diesel_intro\\migrations"
